spring.application.name=backend

# H2 Database (in-memory)
spring.datasource.url=jdbc:h2:mem:outseradb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (desenvolvimento)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

# CSV File
csv.file=Movielist.csv